#!/usr/bin/env ruby


class ContainerMaker
  attr_accessor :lxc, :name

  def initialize(name)
    @name = name
    @lxc = Lxc.new
  end

  def create_if_needed
    lxc.create_container(name) unless lxc.container_exists?(name)
  end

  def add_public_key
    `lxc file push #{public_key_file} #{name}/root/.ssh/authorized_keys`
    lxc.run_command(name, "chmod 0600 /root/.ssh/authorized_keys")
    lxc.run_command(name, "chown root:root /root/.ssh/authorized_keys")
  end

  def public_key_file
    home_dir = ENV["HOME"]
    "#{home_dir}/.ssh/id_rsa.pub"
  end
end

class Lxc
  def default_image
    "ubuntu:16.04"
  end

  def run_command(container_name, command)
    `lxc exec #{container_name} -- #{command}`
  end

  def container_exists?(container_name)
    lines_with_container = `lxc list | grep ' #{container_name} '`
    lines_with_container.size > 0
  end

  def create_container(container_name)
    puts "Creating container #{container_name}"
    command = "lxc launch #{default_image} #{container_name}"
    `lxc launch #{default_image} #{container_name}`
  end
end

container_name = ARGV[0]
puts "container_name: #{container_name}"
maker = ContainerMaker.new(container_name)
maker.create_if_needed
maker.add_public_key
